### ISSUE TITLE
Broke in Firefox 102 

### ISSUE THREAD

**Issue by albert-ying** [typkrft/Poison-Firefox-Theme#3]
Hi! This is a real issue:

I just updated to Firefox 102 recently and the modified custom CSS stop working (after I enabled the custom CSS).

**Comment by albert-ying** [comment]
<img width="991" alt="image" src="https://user-images.githubusercontent.com/59846322/177043711-20323e68-6013-4f26-894e-5c247396d951.png">

**Comment by Ducky6944** [comment]
I'm using 103.0b(eta). It still works for me. I haven't seen any posts about 102 for firefox, but I have seen some people talk about 102 on thunderbird breaking userChrome.css. Maybe it's related to that.

**Comment by albert-ying** [comment]
Thank you for the info! I will try to update to 103 beta then!

**Comment by albert-ying** [comment]
Works again!
